// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlXqKutoHrplP9XFcazBiEs11tfSjBqQ8',
    appId: '1:246854620973:web:aa0085357b5e435557a5a4',
    messagingSenderId: '246854620973',
    projectId: 'stayfit-app-301da',
    authDomain: 'stayfit-app-301da.firebaseapp.com',
    storageBucket: 'stayfit-app-301da.appspot.com',
    measurementId: 'G-72F9SMG31T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrIdMO9ucHPeAnDQXHRKXvy1J7DC3L_Y',
    appId: '1:246854620973:android:d6730e41a28f848c57a5a4',
    messagingSenderId: '246854620973',
    projectId: 'stayfit-app-301da',
    storageBucket: 'stayfit-app-301da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEUFUu7fCKtnWMgUHDhik1KWDF0SZ-PM',
    appId: '1:246854620973:ios:cf08b01e0764b78057a5a4',
    messagingSenderId: '246854620973',
    projectId: 'stayfit-app-301da',
    storageBucket: 'stayfit-app-301da.appspot.com',
    iosClientId: '246854620973-0lrudvk1hmgnv782so6v250c96fad53n.apps.googleusercontent.com',
    iosBundleId: 'com.rmgoktas.stayFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEEUFUu7fCKtnWMgUHDhik1KWDF0SZ-PM',
    appId: '1:246854620973:ios:cf08b01e0764b78057a5a4',
    messagingSenderId: '246854620973',
    projectId: 'stayfit-app-301da',
    storageBucket: 'stayfit-app-301da.appspot.com',
    iosClientId: '246854620973-0lrudvk1hmgnv782so6v250c96fad53n.apps.googleusercontent.com',
    iosBundleId: 'com.rmgoktas.stayFit',
  );
}
